### ISSUE TITLE
Feature request: Consider a rewrite in python2.7?

### ISSUE THREAD

**Issue by Viss** [klustic/AlmondRocks#1]
Using this on security engagements is great for when I find a host that has python3, but those are pretty seldom.

Eeeeeeeverything has python2.7 though.
This tool would be supremely useful if there was a python 2.7 port. 

I would be super grateful if you would consider it! :D

**Comment by Viss** [comment]
Oh. I just noticed the other branch where you have the python2 version of the client
Perfect!

**Comment by klustic** [comment]
Thanks for the feedback! Yeah I've been meaning to clean it up a bit and improve Python 2/3 compatibility but...

**Comment by Viss** [comment]
so I'm on a gig right now and what I've been trying to do is find a way to tunnel ssh out over almondrocks. It's been kinda challenging since the computers are all centos and macs and none have python3 installed ;b

**Comment by klustic** [comment]
@Viss As of Version 1.0 this has been rewritten in Python 2.7 (and is much more stable)
